Development: true

InventoryDatabase:
  master:
    host: "localhost"
    port: 5432
    user: "postgres"
    password: "postgres"
    databaseName: "monosvc_inventory"
    ssl: false
  slave:
    host: "localhost"
    port: 5432
    user: "postgres"
    password: "postgres"
    databaseName: "monosvc_inventory"
    ssl: false

HttpServer:
  address: "localhost:8080"
  readHeaderTimeout: 1s
  readTimeout: 2s
  writeTimeout: 2s
  idleTimeout: 1s

HttpCors:
  allowedOrigins:
    - "http://localhost:8080"
  allowedMethods:
    - "POST"
    - "GET"
    - "PATCH"
    - "PUT"
    - "DELETE"
  allowedHeaders:
    - "Authorization"
  exposedHeaders:
    - "x-request-id"
  maxAge: "65000"
  allowCredentials: true
  optionsPassthrough: true
  debug: false

Grace:
  upgradeTimeout: 10s
  shutdownTimeout: 10s
  network: "tcp"