version: '3.8'
services:
  db:
    image: postgres:13.3-alpine
    container_name: db
    restart: always
    environment:
      POSTGRES_DB: monosvc
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  dbdata:
    driver: local
  redisdata:
    driver: local