package sql

const (
	EcodeStoreAccountClassFailed = iota + 1
	EcodeUpdateAccountClassFailed
	EcodeDeleteAccountClassFailed
	EcodeGetAccountClassListFailed
	EcodeGetAccountClassFailed
	EcodeStoreAccountGroupFailed
	EcodeUpdateAccountGroupFailed
	EcodeDeleteAccountGroupFailed
	EcodeGetAccountGroupFailed
	EcodeGetAllTopLevelAccountGroupFailed
	EcodeGetAllAccountGroupFailed
	EcodeParentIDNotValid
)
