package sql

const (
	EcodeStoreAccountClassFailed = iota + 1
	EcodeUpdateAccountClassFailed
	EcodeDeleteAccountClassFailed
	EcodeGetAccountClassListFailed
	EcodeGetAccountClassFailed
	EcodeStoreAccountGroupFailed
	EcodeUpdateAccountGroupFailed
	EcodeDeleteAccountGroupFailed
	EcodeGetAccountGroupFailed
	EcodeGetAllTopLevelAccountGroupFailed
	EcodeGetAllAccountGroupsFailed
	EcodeParentIDNotValid
	EcodeStoreAccountFailed
	EcodeUpdateAccountFailed
	EcodeDeleteAccountFailed
	EcodeGetAllAccountsFailed
	EcodeGetAccountFailed
	EcodeStoreJournalFailed
	EcodeBeginTxFailed
	EcodeRollbackTxFailed
	EcodeStoreTransactionAtJournalFailed
	EcodeStoreTransactionAtGeneralLedgerFailed
	EcodeStoreTransactionCreatedByRequired
	EcodeTransactionNotBalance
)
