// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Paging struct {
	CurrentPage uint `json:"currentPage"`
	PageSize    uint `json:"pageSize"`
	Total       uint `json:"total"`
}

type PagingInput struct {
	CurrentPage uint `json:"currentPage"`
	PageSize    uint `json:"pageSize"`
}
