// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AccountClassInput struct {
	ID int `json:"id"`
}

type AccountClassesInput struct {
	Paging *PagingInput `json:"paging"`
}

type AccountClassesResult struct {
	Data   []*AccountClass `json:"data"`
	Paging *Paging         `json:"paging"`
}
